project_id = "tcdfyajrywylkhqdefbp"

[functions.ask]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.ingest]
verify_jwt = false

[functions.ingest_from_storage]
verify_jwt = false

[functions.rag_health]
verify_jwt = false
